name: Sync Production

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Push to production
        env:
          PROD_REPO_TOKEN: ${{ secrets.PROD_REPO_TOKEN }}
        run: |
          git remote add production https://x-access-token:${PROD_REPO_TOKEN}@github.com/infotechnysclagos/cdsconnect.git
          git push production main
